### ISSUE TITLE
Black gap under navigation bar

### ISSUE THREAD

**Issue by christstuart** [mcmatan/ImageOpenTransition#9] opened 2016-11-04 04:47 UTC
We I use pushViewController I get a black gap under the navigation bar

**Comment by mcmatan** [comment] 2016-11-07 06:59
Can you give more details/ sample project that this happens to you? Did you check to see how the example project works?

**Comment by mcmatan** [comment] 2016-11-21 13:49
Closing this issue, since can not reproduce and getting no answer. @christstuart 
If anyone notices this issue, please reopen. 
Thanks.

**Closed as completed by mcmatan** 2016-11-21 13:49 UTC
